http:
  middlewares:
    authelia:
      forwardAuth:
        address: 'http://127.0.0.1:9091/api/authz/forward-auth'
        trustForwardHeader: true
        authResponseHeaders:
          - 'Remote-User'
          - 'Remote-Groups'
          - 'Remote-Email'
          - 'Remote-Name'

  routers:
    authelia:
      rule: "Host(`auth.borisovai.ru`) || Host(`auth.borisovai.tech`)"
      service: authelia
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    authelia:
      loadBalancer:
        servers:
          - url: 'http://127.0.0.1:9091'
