http:
  middlewares:
    gitlab-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Ssl: "on"

    gitlab-compress:
      compress:
        excludedContentTypes:
          - "text/event-stream"

    gitlab-buffering:
      buffering:
        maxRequestBodyBytes: 0
        maxResponseBodyBytes: 0

  routers:
    gitlab:
      rule: "Host(`gitlab.dev.borisovai.ru`) || Host(`gitlab.dev.borisovai.tech`)"
      service: gitlab
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - gitlab-headers
        - gitlab-compress
        - gitlab-buffering

  serversTransports:
    gitlab-transport:
      forwardingTimeouts:
        dialTimeout: "30s"
        responseHeaderTimeout: "600s"
        idleConnTimeout: "600s"

  services:
    gitlab:
      loadBalancer:
        serversTransport: gitlab-transport@file
        responseForwarding:
          flushInterval: "100ms"
        servers:
          - url: "http://127.0.0.1:8888"
