http:
  middlewares:
    management-ui-compress:
      compress:
        excludedContentTypes:
          - "text/event-stream"

  routers:
    management-ui:
      rule: "Host(`admin.borisovai.ru`) || Host(`admin.borisovai.tech`)"
      service: management-ui
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - management-ui-compress

  services:
    management-ui:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000"
