http:
  routers:
    scada-prototypes:
      rule: Host(`scada-prototypes.borisovai.tech`) || Host(`scada-prototypes.borisovai.ru`)
      service: scada-prototypes
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
  services:
    scada-prototypes:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:4011
