http:
  routers:
    trend-analisis:
      rule: Host(`cascade.dev.borisovai.tech`) || Host(`cascade.dev.borisovai.ru`)
      service: trend-analisis
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
  services:
    trend-analisis:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:4010
