http:
  routers:
    tunnels:
      rule: "HostRegexp(`^.+\\.tunnel\\.borisovai\\.ru$`) || HostRegexp(`^.+\\.tunnel\\.borisovai\\.tech$`)"
      service: tunnel-frp
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      priority: 1

  services:
    tunnel-frp:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://127.0.0.1:17480"
